
export const FETCH_RESTORANTS_START = 'FETCH_RESTORANTS_START'
export const FETCH_RESTORANTS_SUCCESS = 'FETCH_RESTORANTS_SUCCESS'
export const FETCH_RESTORANTS_ERROR = 'FETCH_RESTORANTS_ERROR'

export const CART_OPEN = 'CART_OPEN'
export const CART_CLOSE = 'CART_CLOSE'

export const ADD_REMOVE_TO_CART = 'ADD_REMOVE_TO_CART'

export const CART_BTN_BLOCK = 'CART_BTN_BLOCK'
export const CART_BTN_NO_BLOCK = 'CART_BTN_NO_BLOCK'

export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_ERROR = 'AUTH_ERROR'
export const AUTH_ADMIN = 'AUTH_ADMIN'
export const AUTH_NO_ADMIN = 'AUTH_NO_ADMIN'

export const AUTH_MODAL_OPEN = 'AUTH_MODAL_OPEN'
export const AUTH_MODAL_CLOSE = 'AUTH_MODAL_CLOSE'

export const ADMIN_MODAL_TYPE_RESTORANT_SET = 'ADMIN_MODAL_TYPE_RESTORANT_SET'
export const ADMIN_MODAL_TYPE_MENU_SET = 'ADMIN_MODAL_TYPE_MENU_SET'
export const ADMIN_MODAL_OPEN = 'ADMIN_MODAL_OPEN'
export const ADMIN_MODAL_CLOSE = 'ADMIN_MODAL_CLOSE'
export const ADMIN_MESSAGE = 'ADMIN_MESSAGE'

export const ADMIN_GET_ORDERS = 'ADMIN_GET_ORDERS'
