
export const FETCH_RESTORANTS_START = 'FETCH_RESTORANTS_START';
export const FETCH_RESTORANTS_SUCCESS = 'FETCH_RESTORANTS_SUCCESS';
export const FETCH_RESTORANTS_ERROR = 'FETCH_RESTORANTS_ERROR';

export const CART_OPEN = 'CART_OPEN';
export const CART_CLOSE = 'CART_CLOSE';


export const ADD_REMOVE_TO_CART = 'ADD_REMOVE_TO_CART';
export const RESET_CART ='RESET_CART';

export const ADD_BTN_TO_CART ='ADD_BTN_TO_CART';
export const REMOVE_BTN_TO_CART ='REMOVE_BTN_TO_CART';




export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const AUTH_MODAL_OPEN='AUTH_MODAL_OPEN';
export const AUTH_MODAL_CLOSE='AUTH_MODAL_CLOSE';


